"""add urls profile

Revision ID: 1c61a7c59418
Revises: 
Create Date: 2023-09-02 01:06:35.157714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c61a7c59418'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('github_url', sa.String(length=200), nullable=True))
    op.add_column('user_data', sa.Column('twitter_url', sa.String(length=200), nullable=True))
    op.add_column('user_data', sa.Column('personal_website', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'personal_website')
    op.drop_column('user_data', 'twitter_url')
    op.drop_column('user_data', 'github_url')
    # ### end Alembic commands ###
